name: Test neurocommand
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
    
jobs:
  test_neurocommand:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
      with:
        python-version: 3.8
    - name: Test neurocommand version
      run: /bin/bash .github/workflows/test_neurocommand.sh
