name: Update neurocontainers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-neurocontainers.yml'
      - 'neurodesk/apps.json'
      - 'neurodesk/write_log.py'

jobs:
  upload_containers_simg:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
      with:
        python-version: 3.8
    - name: Configure AWS Credentials 1
      id: creds
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
      with:
        aws-region: us-east-2
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        output-credentials: true
        role-duration-seconds: 28800 # 8 hours
    - name : Check if singularity container files exist in nectar cloud and build & upload if not there
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
      run: |
        rclone config create aws-neurocontainers-new s3 config_is_local false provider AWS env_auth true
        /bin/bash .github/workflows/upload_containers_simg.sh
    - name: Auto commit changes to applist.json
      uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79
      id: auto-commit-action
    - name: "Run if changes found to applist.json"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: |
          curl -X POST https://api.github.com/repos/NeuroDesk/neurodesk.github.io/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "NeuroDesk/neurocommand applist.json update"}'